Traceback (most recent call last):
  File "/Users/mriki/workspace/prpy/.venv/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/mriki/workspace/prpy/.venv/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mriki/workspace/prpy/.venv/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mriki/.rye/py/cpython@3.11.8/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/mriki/workspace/prpy/.venv/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/mriki/workspace/prpy/.venv/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/mriki/workspace/prpy/.venv/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def 仮の関数3():
    a -= 10
    print("仮の関数3内で変数aを定義：",a)

仮の関数3()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mUnboundLocalError[0m                         Traceback (most recent call last)
Cell [0;32mIn[9], line 5[0m
[1;32m      2[0m     a [38;5;241m-[39m[38;5;241m=[39m [38;5;241m10[39m
[1;32m      3[0m     [38;5;28mprint[39m([38;5;124m"[39m[38;5;124m仮の関数3内で変数aを定義：[39m[38;5;124m"[39m,a)
[0;32m----> 5[0m [43m仮の関数3[49m[43m([49m[43m)[49m

Cell [0;32mIn[9], line 2[0m, in [0;36m仮の関数3[0;34m()[0m
[1;32m      1[0m [38;5;28;01mdef[39;00m [38;5;21m仮の関数3[39m():
[0;32m----> 2[0m     [43ma[49m [38;5;241m-[39m[38;5;241m=[39m [38;5;241m10[39m
[1;32m      3[0m     [38;5;28mprint[39m([38;5;124m"[39m[38;5;124m仮の関数3内で変数aを定義：[39m[38;5;124m"[39m,a)

[0;31mUnboundLocalError[0m: cannot access local variable 'a' where it is not associated with a value

